### PR TITLE
Improving accessibility; updating text and links

### PR DESCRIPTION
**Pull request by RoisinF**

### CODE REVIEW

**Comment by chrisdeans** [comment]
Is the plan to do the stays -> spells changes in a separate commit?

**Comment by RoisinF** [comment]
> Is the plan to do the stays -> spells changes in a separate commit?

No, I just forgot to put it in this version! I'll fix it now.

**Review by chrisdeans — APPROVED** [review]
Looks good to me.

**Review by evelyn-shiel — APPROVED** [review]

**Comment by evelyn-shiel** [comment]
Hi, Kirsty has asked could we put "Specialty breakdowns are measured in episode and spells rather than stays. For more information, please see the methodology section" on the table tab with a link to the methodology section. Would this be possible or should we do it on another pull request?

**Comment by evelyn-shiel** [comment]
> Hi, Kirsty has asked could we put "Specialty breakdowns are measured in episode and spells rather than stays. For more information, please see the methodology section" on the table tab with a link to the methodology section. Would this be possible or should we do it on another pull request?

Sorry I should've mentioned this earlier, for some reason I thought you knew, clearly through telelpathy! Hahaha

**Review by evelyn-shiel — APPROVED** [review]

**Pull request merged**
